### ISSUE TITLE
No longer need to unset PIP_REQUIRE_VIRTUALENV

### ISSUE THREAD

**Issue by jondricek** [asdf-community/asdf-poetry#13]
There is a comment https://github.com/asdf-community/asdf-poetry/blob/6176ff26132170c74a9daf1044e7d5ac62fe7546/bin/install#L25-L28 that says the `PIP_REQUIRE_VIRTUALENV` environment variable being unset can be removed once https://github.com/python-poetry/poetry/issues/4089 has been resolved. Well, just the other day it was fixed! Just thought I'd do my civic duty and report it.

**Comment by tony** [comment]
@jondricek Regarding https://github.com/python-poetry/poetry/commit/8dc83b373a79d376b561f47fa5534f6db7b558ad

This is going to the `install-poetry.py` itself.  Does this bug also apply to get-poetry.py (which is used for older versions of poetry)
