### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by bfmcneill** [asdf-community/asdf-poetry#6]
Does this assist with creating virtual environments?  I am a little confused with how to use this.  Any tips?  Thanks!

**Comment by smorimoto** [comment]
This is a version manager that maintains a version of a package manager called Poetry, so you should ask the Poetry team about it in the first place. Well, it does. You can also disable it.
https://python-poetry.org/docs/faq/#i-dont-want-poetry-to-manage-my-virtual-environments-can-i-disable-it
